log-level: debug  # debug | info | warn | error

# modules:
#   spark:
#     version: 1.3.0  # can also be a git hash
#     git-repo: "https://github.com/apache/spark"  # required only if deploying a hash
#   ephemeral-hdfs:
#     version: 
#   tachyon:
#     version: 

provider: ec2

launch:
  num-slaves: 1
  # spark-version: 1.3.0

  ec2-key-name: nick
  ec2-identity-file: /Users/nicholaschammas/.ssh/nick.pem
  ec2-instance-type: m3.medium  # must be 64-bit; small instances won't work
  ec2-region: us-east-1
  # ec2-availability-zone: <name>
  ec2-ami: ami-146e2a7c
  # ec2-spot-price: <price>
  # ec2-vpc-id: <id>
  # ec2-subnet-id: <id>
  # ec2-placement-group: <name>
  ec2-tenancy: default  # default | dedicated
  ec2-ebs-optimized: no  # yes | no
  ec2-instance-initiated-shutdown-behavior: terminate  # terminate | stop
  # ec2-delete-groups-on-destroy: no  # yes | no

login:
  ec2-identity-file: /Users/nicholaschammas/.ssh/nick.pem

describe:
  ec2-region: us-east-1

# ssh-user: root
# use-existing-master: no
# ec2:
#   master-instance-type:  # leave empty for same as instance-type
#   ebs-volumes:
#     count: 0  # N volumes get attached as /vol[N]
#     size-gb: 8
#     type: standard  # gp2, standard
#   security-group-ids: 
#   instance_profile_arn: 
